name: pdf
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - annotated-doc=0.0.4=py312hca03da5_0
  - annotated-types=0.6.0=py312hca03da5_1
  - anyio=4.10.0=py312hca03da5_0
  - brotlicffi=1.1.0.0=py312h50f4ffc_0
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.11.4=hca03da5_0
  - certifi=2025.11.12=py312hca03da5_0
  - cffi=2.0.0=py312h73c2a22_1
  - charset-normalizer=3.4.4=py312hca03da5_0
  - click=8.2.1=py312hca03da5_0
  - expat=2.7.3=h982b769_0
  - fastapi=0.121.1=py312hf834670_0
  - h11=0.16.0=py312hca03da5_1
  - idna=3.11=py312hca03da5_0
  - libcxx=20.1.8=hd7fd590_1
  - libffi=3.4.4=hca03da5_1
  - libzlib=1.3.1=h5f15de7_0
  - ncurses=6.5=hee39554_0
  - openssl=3.0.18=h9b4081a_0
  - pip=25.3=pyhc872135_0
  - pycparser=2.23=py312hca03da5_0
  - pydantic=2.12.3=py312hca03da5_1
  - pydantic-core=2.41.4=py312h108b7f8_0
  - pypdf=6.0.0=py312hca03da5_0
  - pysocks=1.7.1=py312hca03da5_1
  - python=3.12.12=h2bfc596_1
  - python-multipart=0.0.20=py312hca03da5_0
  - readline=8.3=h0b18652_0
  - requests=2.32.5=py312hca03da5_1
  - setuptools=80.9.0=py312hca03da5_0
  - sniffio=1.3.0=py312hca03da5_0
  - sqlite=3.51.0=hab6afd1_0
  - starlette=0.47.3=py312hca03da5_0
  - tk=8.6.15=hcd8a7d5_0
  - typing-extensions=4.15.0=py312hca03da5_0
  - typing-inspection=0.4.2=py312hca03da5_0
  - typing_extensions=4.15.0=py312hca03da5_0
  - tzdata=2025b=h04d1e81_0
  - urllib3=2.5.0=py312hca03da5_0
  - uvicorn=0.35.0=py312hca03da5_0
  - wheel=0.45.1=py312hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
  - pip:
      - httpcore==1.0.9
      - httpx==0.28.1
      - ollama==0.6.1
prefix: /opt/anaconda3/envs/pdf
